### ISSUE TITLE
Loading covers creates duplicates in Playnite's metadata folder

### ISSUE THREAD

**Issue by CanRanBan** [roob-p/CoverStyleSwitcher-PlayniteExtension#2]
Using the menu of `Cover Style Switcher` to `Load` one of the slots will create duplicates of the same image inside Playnite's own metadata folder.
The extension does not replace the existing cover as expected in Playnite's metadata folder with the chosen one and rather adds an additional image without removing the previous one.
Alternating between multiple slots or using the same slot each time makes no difference.

**Comment by roob-p** [comment]
Hi, thanks for reporting this issue. Fixed with v1.0.3
